[build]
publish = "public"
command = "hugo --gc --minify -b $URL/"

[context.production.environment]
  HUGO_VERSION = "0.98.0"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.98.0"
  HUGO_ENABLEGITINFO = "true"
